### ISSUE TITLE
Pre-Trained Model checkpoints available?

### ISSUE THREAD

**Issue by Axe--** [jackroos/VL-BERT#22]
I would like to run the evaluation scrtipt on VCR dataset `vcr/val.py`, but not sure about the checkpoint files `--a-ckpt` & `--r-ckpt`.
Could kindly assist me with this issue. 

For the given template:
```
python vcr/val.py \
  --a-cfg <cfg_of_q2a> --r-cfg <cfg_of_qa2r> \
  --a-ckpt <checkpoint_of_q2a> --r-ckpt <checkpoint_of_qa2r> \
  --gpus <indexes_of_gpus_to_use> \
  --result-path <dir_to_save_result> --result-name <result_file_name> 
```
This is what I am executing:
```
python3 vcr/val.py \
--a-cfg ./cfgs/vcr/base_q2a_4x16G_fp32.yaml \
--r-cfg ./cfgs/vcr/base_qa2r_4x16G_fp32.yaml \
--gpus 0 1 --result-path ./results/ --result-name eval_vcr \
--a-ckpt ./model/pretrained_model/vl-bert-base-e2e.model
```
However I am facing the following error:
```
Traceback (most recent call last):
  File "vcr/val.py", line 218, in <module>
    main()
  File "/home/axe/VirtualEnvs/py3ve/lib/python3.6/site-packages/torch/autograd/grad_mode.py", line 49, in decorate_no_grad
    return func(*args, **kwargs)
  File "vcr/val.py", line 119, in main
    smart_load_model_state_dict(answer_model, a_ckpt['state_dict'])
  File "/home/axe/Projects/VL_BERT/common/utils/load.py", line 16, in smart_load_model_state_dict
    raise ValueError('failed to match key of state dict smartly!')
ValueError: failed to match key of state dict smartly!
```
This is my `./models` directory:
```
└── pretrained_model
    ├── bert-base-uncased
    │   ├── bert_config.json
    │   ├── pytorch_model.bin
    │   └── vocab.txt
    ├── bert-large-uncased
    │   ├── bert_config.json
    │   ├── pytorch_model.bin
    │   └── vocab.txt
    ├── PREPARE_PRETRAINED_MODELS.md
    ├── resnet101-pt-vgbua-0000.model
    └── vl-bert-base-e2e.model
```

**Comment by jackroos** [comment]
@Axe-- These pre-trained models mean pre-training on Conceptual-Captions and text-only corpus, not on downstream tasks, like VCR. Please use [configs for VCR](https://github.com/jackroos/VL-BERT/tree/master/cfgs/vcr) to fine-tune VL-BERT before you evaluate them on VCR. Thanks!

**Comment by Axe--** [comment]
Oh! Got it. Thank you! :-)

**Comment by liulijie-2020** [comment]
> Oh! Got it. Thank you! :-)

Excuse me.What the final checkpoint files are?Are they through training in the Folder“output”?And which should i add following --a-ckpt & --r-ckpt.
